title: Antone King
description: Enterprise AI, computer vision, and experiments on a small farm. Notes and projects by Antone King.
baseurl: ""
url: "https://antonemking.github.io"
author: Antone King
email: toneking972@gmail.com
twitter_username: antoneking
github_username: antonemking

theme: minima
minima:
  skin: classic

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

show_excerpts: true

lang: en
exclude:
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock
